apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sendresults-service
  name: sendresults-service
spec:
  ports:
  - name: sendresults-port
    port: 80
    protocol: TCP
    targetPort: 9095
  selector:
    app: sendresults-service
  type: NodePort
status:
  loadBalancer: {}
